import React from 'react';
import { DocsLayout } from '../../../layouts/DocsLayout';

export default function CompanyConfigurationPage() {
  return (
    <DocsLayout>
      <div>
        <h1 className="text-3xl font-bold mb-6">Company Configuration Management</h1>
        <p className="text-gray-600 text-lg mb-8">
          This feature provides Company Admins with tools to configure company-wide settings and policies on the YuVi 
          platform. It encompasses various aspects of company operation, from basic profile management to security policies 
          and integration settings. Through this feature, Company Admins can maintain company information and branding, 
          configure security parameters like password policies and session management, set up communication preferences, and 
          manage external integrations. The feature ensures consistent application of policies across the company's platform 
          usage while allowing flexibility where needed. It handles critical security configurations including authentication 
          rules, MFA requirements, and IP access restrictions. The feature also manages audit logging configurations and 
          integration settings with external systems. These configurations establish the operational framework within which 
          all platform activities for the company take place.
        </p>

        <section className="mb-12">
          <h2 className="text-2xl font-semibold mb-6">Use Cases</h2>
          <div className="space-y-6">
            <div className="p-6 bg-white rounded-lg shadow-sm border border-gray-100">
              <h3 className="text-xl font-medium text-gray-900 mb-4">Company Profile Management</h3>
              <p className="text-gray-600">
                This use case enables Company Admins to manage their company's core information and branding on the platform. 
                It includes updating company identification information including name, description, and address details. The 
                use case also handles company brand asset management, allowing upload and configuration of visual elements 
                like logos and color schemes. These configurations affect how the company's instance of the platform appears 
                to its users. The use case ensures proper validation of all information and maintains change history in the 
                audit log.
              </p>
            </div>

            <div className="p-6 bg-white rounded-lg shadow-sm border border-gray-100">
              <h3 className="text-xl font-medium text-gray-900 mb-4">Account Security Configuration</h3>
              <p className="text-gray-600">
                This use case manages company-wide security settings on the platform. It includes configuration of password 
                policies, session lock rules, concurrent session limits, multi-factor authentication requirements, account 
                lockout policies, and IP access restrictions. Company Admins can set security parameters that meet their 
                organization's requirements while ensuring they meet platform minimum security standards. The use case ensures 
                comprehensive security control while maintaining usability. All security configurations are properly validated 
                and logged, creating a secure but manageable environment for company operations.
              </p>
            </div>

            <div className="p-6 bg-white rounded-lg shadow-sm border border-gray-100">
              <h3 className="text-xl font-medium text-gray-900 mb-4">Communication Settings</h3>
              <p className="text-gray-600">
                This use case manages company-wide communication configurations on the platform. It enables Company Admins to 
                configure email settings, notification preferences, and communication templates that will be used across the 
                platform. The settings determine how the system communicates with users for various events and notifications. 
                The use case includes configuration of email servers, notification delivery preferences, and management of 
                standardized message templates. These settings ensure consistent and reliable communication for 
                system-generated messages while maintaining proper delivery tracking and logging. The configurations apply to 
                all automated communications generated by the platform for the company's users.
              </p>
            </div>

            <div className="p-6 bg-white rounded-lg shadow-sm border border-gray-100">
              <h3 className="text-xl font-medium text-gray-900 mb-4">Company Default Localization</h3>
              <p className="text-gray-600">
                The Company Default Localization use case enables companies to establish standardized regional settings that 
                serve as defaults across their YuVi platform instance. Through this use case, Company Admins can configure 
                fundamental localization parameters that affect how users across the company interact with the platform. The 
                use case manages configuration of core regional settings including default language, time zone, and various 
                format preferences. Companies can set their preferred formats for dates (e.g., DD/MM/YYYY), times (12/24 
                hour), numbers (decimal/thousand separators), and currency (symbol position, decimal places). Additional 
                settings include first day of week preference and measurement units (metric/imperial), ensuring consistency 
                with regional business practices. These settings serve as the company-wide defaults, automatically applying 
                to all new spaces and users created in the platform. Existing spaces retain their current settings, 
                maintaining operational continuity while allowing for space-specific customization when needed.
              </p>
            </div>

            <div className="p-6 bg-white rounded-lg shadow-sm border border-gray-100">
              <h3 className="text-xl font-medium text-gray-900 mb-4">Company Default Access Governance</h3>
              <p className="text-gray-600">
                The Company Default Access Governance use case enables companies to establish standardized access control 
                policies and documentation requirements across their YuVi platform instance. Through this use case, Company 
                Admins can configure how access changes are reviewed, documented, and approved throughout the organization. 
                The use case manages the configuration of periodic access reviews, setting standard frequencies and scopes 
                for reviewing user access across the platform. Companies can define when reviews must occur, what aspects of 
                access need review, and how review outcomes should be documented. The system enforces these review cycles 
                and maintains comprehensive records of review completions and decisions. For access changes, the use case 
                allows companies to set global documentation requirements, determining whether all access modifications need 
                justification or only specific types.
              </p>
            </div>
          </div>
        </section>
      </div>
    </DocsLayout>
  );
}